"use strict";
/**
 * Fitness Meetup
 * The public API for the FitnessMeetup platform
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
class Meetup {
    static getAttributeTypeMap() {
        return Meetup.attributeTypeMap;
    }
}
Meetup.discriminator = undefined;
Meetup.attributeTypeMap = [
    {
        "name": "id",
        "baseName": "id",
        "type": "number"
    },
    {
        "name": "title",
        "baseName": "title",
        "type": "string"
    },
    {
        "name": "description",
        "baseName": "description",
        "type": "string"
    },
    {
        "name": "sport",
        "baseName": "sport",
        "type": "string"
    },
    {
        "name": "owner",
        "baseName": "owner",
        "type": "User"
    },
    {
        "name": "participants",
        "baseName": "participants",
        "type": "Array<User>"
    },
    {
        "name": "date",
        "baseName": "date",
        "type": "Date"
    },
    {
        "name": "location",
        "baseName": "location",
        "type": "Location"
    }
];
exports.Meetup = Meetup;
//# sourceMappingURL=meetup.js.map