/*
 * Fitness Meetup
 *
 * The public API for the FitnessMeetup platform
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using Microsoft.AspNetCore.Mvc;
using FitnessMeetupApi.Service.Attributes;
using FitnessMeetupApi.Persistence;

namespace FitnessMeetupApi.Service.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    public class SportsApiController : ControllerBase
    {
        private readonly ISportsRepository sports;

        public SportsApiController(ISportsRepository sports)
        {
            this.sports = sports;
        }

        /// <summary>
        /// Get the sports categories that are supported by the server.
        /// </summary>
        /// <response code="200">Successfully retrieved all sports categories.</response>
        [HttpGet]
        [Route("/v1/sports")]
        [ValidateModelState]
        public virtual IActionResult GetAllSports()
        {
            return new ObjectResult(sports.GetSports());
        }
    }
}
